### ISSUE TITLE
okta-angular: Callback with Query String Parameters

### ISSUE THREAD

**Issue by th3n3wguy** [okta/okta-oidc-js#123]
Problem:

- When using the `okta-angular` package, if a user's session is timed out, they are redirected to the Okta login page with a callback URL that contains query-string parameters. The problem is that the query string parameters are being converted using, what I assume to be, something like JavaScript's [encodeURIComponent](https://www.w3schools.com/jsref/jsref_encodeuricomponent.asp). All of the `?` and `&` and other symbols are converted, which breaks our UI application's URLs when the callback is handled within the `okta-angular` library to handle the redirect after a successful login.

Solution:

- No idea how to help here as I don't have the time to go through the code repository to find the exact lines of code that are handling this functionality. I apologize for not doing further code analysis, but hopefully you will be able to resolve this issue fairly quickly.

**Comment by jmelberg-okta** [comment]
Hey @th3n3wguy! I want to get a bit more info on how you're using the `okta-angular` library.

Just for clarification, by default, the `loginRedirect` method performs the [Implicit Flow](https://developer.okta.com/authentication-guide/implementing-authentication/implicit), which is required to return the tokens back via a hash fragment. Is this the flow you're using?

Secondly, I'm assuming you've setup a redirect URI in Okta and your SPA to be formatted **with** query params. For example: `https://mysite.com/callback?q=someState`. After successful login, the tokens are appended to the callback URI similar to: `https://mysite.com/callback?q=someState#accessToken=ey...`.

Is the issue here that the specified callback includes the encoded query params, or is this only an issue when attempting to parse the tokens from the URL?

**Comment by th3n3wguy** [comment]
What is happening for us is that if we call the `OktaAuthService.loginRedirect()` function from any page that contains query string parameters (e.g. `https://myui.sample.com/page1?q=test&base=super`), then we are redirected to the Okta login page and that workflow is functioning just fine, but as soon as the application redirects us back to the original page, the URL comes out looking like this:
- `https://myui.sample.com/page1%3Fq%3Dtest%26base%3Dsuper`

Then, Angular has no idea how to get the query string parameters because it doesn't recognize those HTML-encoded characters as query string parameters, so the page does not reload properly. In the meantime, we have it set up where pages automatically redirect back to our home page after re-authenticating with Okta, but this is not an ideal scenario for the long-term.

**Comment by jmelberg-okta** [comment]
Hey @th3n3wguy.

Sorry for the delay. This issue is due to how we're handling the router navigation when redirecting back to a page protected by `canActivate`.

I'm pushing a fix for this under the `1.0.0-angular` branch - as it'll be a breaking change. I'll follow up once that's pushed live.

**Comment by th3n3wguy** [comment]
Thanks for the information @jmelberg-okta. We will be on the lookout for this change!

**Comment by jmelberg-okta** [comment]
Resolved with #157 and #167
