### ISSUE TITLE
Cannot refresh access token in Firefox

### ISSUE THREAD

**Issue by Wrecklaimer** [okta/okta-oidc-js#124]
The token manager is set up to automatically refresh the current access token periodically. This works as expected in both Chrome and Edge. However, in Firefox, it just returns an error and clear the token form local storage.

This is the error that is logged to the console: `error.errorCode: login_required, error.description: The client specified not to prompt, but the user is not logged in.`

I have even tried manually calling `TokenManager.refresh()`, but the same error occurs.

I am using the Angular package

**Comment by lboyette-okta** [comment]
This is probably due to firefox's 3rd party cookie management. By default, firefox disables 3rd party cookies in private windows. Token refresh requires 3rd party cookies to be enabled for your Okta domain, so if you want to have token refresh in a Private window, you'll need to add your Okta domain (`https://dev-######.oktapreview.com`) to the exceptions.

If you're not in a private window, make sure you either disable **Tracking Protection** or set it to `Only in private windows`.

**Comment by lboyette-okta** [comment]
Related to: https://github.com/okta/okta-auth-js/issues/71

**Comment by Wrecklaimer** [comment]
Looks like that was the issue. Thanks for the quick reply!
