### ISSUE TITLE
Angular sample crashes when built for prod

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-oidc-js#176]
I tried the latest [Angular custom login](https://github.com/okta/samples-js-angular/tree/master/custom-login) sample:

```
git clone git@github.com:okta/samples-js-angular.git
cd samples-js-angular\custom-login
npm i
ng serve
```

This works fine! However:

```
ng serve --prod
```

Compiles fine, but I get this when I visit `http://localhost:8080`:

![image](https://user-images.githubusercontent.com/7525482/38341721-d5f6e386-382e-11e8-9141-01b745b05198.png)

I suspect something in the configuration is getting mistakenly removed by the tree-shaker, but I don't know enough of what I'm talking about to fix it. 😉

**Comment by nbarbettini** [comment]
Original report: https://devforum.okta.com/t/okta-angular-okta-samples-js-angular-sample-applications/1518

**Comment by Wrecklaimer** [comment]
I'm running into this exact issue after recently updating to the latest version of okta-angular.

At first, I thought it was a dependency conflict with okta-signin-widget. But removing that didn't fix the issue.

**Comment by Wrecklaimer** [comment]
@nbarbettini My issue had something to do with the OktaAuthModule not being configured (undefined). It worked with no issues until a prod build. It seemed pretty obvious once I realized the problem, since "issuer" is part of the Okta config object. I'm guess something similar is happening with the sample app.

**Comment by GBrawl** [comment]
Having the exact same problem here, also tried removing the signin-widget, but apparently that's not where the error occurs. Hoping this gets fixed soon

**Comment by ijer-web** [comment]
Please, solve it!

**Comment by Frugoletto** [comment]
Same exact problem.
It's a blocking issue; please give this a chance to get fixed

**Comment by Frugoletto** [comment]
After some trial and error seems I have managed to find almost a workaround. The problem seems linked to the initialization way of the OktaModule, specifically in the 
```
imports:      [
        ...
        OktaAuthModule.initAuth(environment.oktaConfig),
        ...
    ]
```
section of the AppModule file. 
It seems that the AOT compiler does not fully support provider initialization made in that way, so I tried to comment out the initAuth call and move the code directly in providers section, something like:
```
imports:      [
        ...
        OktaAuthModule,//.initAuth(environment.oktaConfig),
        ...
    ],
    providers: [
      ...
      // okta
      {
        provide: OKTA_CONFIG,
        useValue: environment.oktaConfig
      },
      OktaAuthService,
      OktaAuthGuard,
      ...
    ],

```
In this way my application works well, so I will leave things in this way, waiting for a more robust solution

**Comment by sgwatgit** [comment]
Ran into this same issue during development since I'm running `ng serve --aot`.

Saw while debugging that my `environment` values were never being passed to `OktaAuthModule.initAuth`.

Thanks @Frugoletto

**Comment by albertogarza** [comment]
Thanks a lot for the workaround @Frugoletto. I tried it with `"@okta/okta-angular": "1.1.0"` and `"@angular/core": "7.2.6"` today and it's still a valid workaround.

However, this deserves a real fix. Anybody has an update on this issue? It'd be awesome if this works out of the box even with the AOT compiler. Thanks for all the work put in to this!

**Comment by aarongranick-okta** [comment]
Confirmed this is an issue when using the AOT compiler. To reproduce: `ng serve --aot`

**Comment by aarongranick-okta** [comment]
We have updated okta-angular (v1.2.0). It is no longer necessary to call OktaAuthModule.initAuth(). Instead your app should provide OKTA_CONFIG and import OktaAuthModule as described here: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-angular#usage
