### ISSUE TITLE
Possible to use the code flow?

### ISSUE THREAD

**Issue by cmckni3** [okta/okta-oidc-js#187]
>Exchange the authorization code for an access token
To exchange the authorization code for an access token, the app makes a POST request to the service’s token endpoint. The request will have the following parameters.

Per https://www.oauth.com/oauth2-servers/oauth2-clients/single-page-apps/

**Comment by cmckni3** [comment]
Reason I ask is because IE 11 and Edge seem to have trouble with the long URL containing access token.

**Comment by robertjd** [comment]
Also: I'm not sure what your use case is, but perhaps omit the ID token from the authorize request?  You can still use a returned access token to get the same information about the user from the /userinfo endpoint (via the `getUser()` method that our front-end libraries provide)

**Comment by cmckni3** [comment]
Sorry, this is a single page app using Angular. It is running `@okta/okta-angular` 0.1.0.

**Comment by jmelberg-okta** [comment]
Hey @cmckni3,

In order to use this flow in a front-end application (public client), you'll need to use the [PKCE](https://tools.ietf.org/html/rfc7636https://tools.ietf.org/html/rfc7636) protocol to prevent `authorization_code` interception attacks, and omit the `client_secret` when requesting tokens from the `/token` endpoint. There is a good overview of this flow listed on our [developer site](https://developer.okta.com/authentication-guide/implementing-authentication/auth-code-pkce).

We're tracking this issue in the underlying library here: [okta-auth-js #78](https://github.com/okta/okta-auth-js/issues/78). Please feel free to watch that issue for updates!

**Comment by cmckni3** [comment]
@robertjd I tried the `getUser` method but it only returns `sub` and `Groups`. It also requires the ID token in the Angular library. See [here](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/src/okta/services/okta.service.ts#L111)

Also, the ID token comes back even when `openid` is the only specified `scope`.

**Comment by cmckni3** [comment]
Looks like a configuration issue was the culprit. I am working on upgrading to `1.0.0`.

**Comment by cmckni3** [comment]
I am closing this because the authorization code flow isn't what I want for my SPA according to other sources.

I apologize for the confusion. The oauth.com page confused me.
