### ISSUE TITLE
Expose auth JS instance from Angular

### ISSUE THREAD

**Issue by jmelberg-okta** [okta/okta-oidc-js#227]
### Description
- Allow integration libs to leverage `okta-auth-js`'s [`token.refresh`](https://github.com/okta/okta-auth-js#tokenrefreshtokentorefresh) method to force silent refreshing

**Comment by robertjd** [comment]
@jmelberg-okta is the idea here to give developers control to disable auto refresh in authjs, and manually invoke the silent refresh?

**Comment by jmelberg-okta** [comment]
@robertjd - Correct.

There is disparity on how each package initializes the underlying `okta-auth-js` client, so I'm thinking about prioritizing this as follows:

1. Extend constructor params to include `tokenManager` configuration
2. Add `token.refresh` for devs who want the ability to "hard reset" tokens
3. Update **Angular** and **Vue** to follow **React**'s ability to pass in an [**Auth** instance](https://github.com/okta/okta-oidc-js/pull/97)

**Comment by jraadt** [comment]
There are situations where the auto renew doesn't work and manually calling `getWithoutPrompt()` in okta-auth-js and setting the tokens fixes it. It would be great to have this exposed. I modified okta.service.ts in the Angular project to include the following method, which solved this for me and would be great to have included in this project:

```
/**
 * Silently retrieve token.
 * @param additionalParams
 */
async loginSilent(additionalParams?: object) {
  try {
    var tokens = await this.oktaAuth.token.getWithoutPrompt({
      responseType: (this.config.responseType || 'id_token token').split(' '),
      // Convert scopes to list of strings
      scopes: this.config.scope.split(' '),
      ...additionalParams
    });

    for (var a = 0; a < tokens.length; a++) {
      if (tokens[a].idToken) {
        this.oktaAuth.tokenManager.add('idToken', tokens[a]);
      }
      if (tokens[a].accessToken) {
        this.oktaAuth.tokenManager.add('accessToken', tokens[a]);
      }
    }

    if (await this.isAuthenticated()) {
      this.emitAuthenticationState(true)
    }

    return tokens;
  } catch (err) {
    // The user no longer has an existing SSO session in the browser.
    // (OIDC error `login_required`)
    // Ask the user to authenticate again.
    return undefined;
  }
}

```

**Comment by swiftone** [comment]
INFO: This may be related to an error not being properly caught.

**Comment by SushanRajShakya** [comment]
I would love to handle the refreshing of an expired accessToken silently without redirecting the user to login page again (i.e. silently refresh the access tokens using interceptor). With **okta-react** however, there is no way to refresh the accessToken and if you try to go some **SecureRoute** when accessToken has expired it goes to the route but then all the requests then made are returned with a status code of 401 from the server.

Thank you,

**Comment by andkh** [comment]
It would be nice to support loginSilent for @okta/okta-angular. 
@jraadt nice example.

**Comment by swiftone** [comment]
@andkh - Thanks for the update.  While the workaround @jraadt posted works for many, we're more interested in chasing down the original auto-renew failure, otherwise we aren't clear as to why the proposed `loginSilent` will work when the auto-renew didn't.

**Comment by andkh** [comment]
@swiftone Thank you for quick response. You are right it shouldn't do auto-renew. I mean it would be greate to have the 'auto-renew', 'getWithoutPrompt' in @okta/okta-angular.

**Comment by swiftone** [comment]
internal ref: 257120 (and related)

**Comment by hboylan** [comment]
These libraries have access to the underlying okta-auth-js object via `auth._oktaAuth`.

I'd like to use this with the `okta-react` package to silently refresh the token, but am not sure when to make the call to `auth._oktaAuth.token.getWithoutPrompt()`

**Comment by jraadt** [comment]
@aarongranick-okta & @swiftone - Unfortunately this is still an issue with okta-angular 2.0. onSessionExpired doesn't solve all the cases. I have an ASP.NET Core web application that uses the ASP.NET Core Okta SDK to authenticate the user. This works great.

Part of the web application is an Angular application that calls out to a different ASP.NET Core API. I use the okta-angular SDK for the Angular application and unfortunately it has to do full page redirects to get the bearer access tokens it needs instead of a silent login that would work since the user is already SSO into Okta.

I hope that made sense. Could we expose a silent login or is there a different way I should handle a web app + SPA + API?

**Comment by aarongranick-okta** [comment]
@jraadt @andkh @SushanRajShakya 
We make available a couple of function callbacks which could help in this case:
https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/README.md#okta_config

- `config.isAuthenticated` you can supply a function which returns a promise to determine if the user is authenticated or not.  The default logic is very optimistic and does not perform any network request. You could possibly call getWithoutPrompt within this function (the first time it is called, be careful because it could be called frequently)
- `config.onAuthRequired` - if authentication is required, then this function can provide custom logic. You could try getWithoutPrompt (if user is already signed in) or getWithPopup to obtain credentials in a popup window without reloading/redirecting
- `config.onSessionExpired` - occurs after a permanent failure to renew a token (there is a point at which tokens cannot be auto renewed and the user MUST provide credentials to create a new session). The default logic will call `login` which will call `onAuthRequired` if it is defined.

The token renew logic will run whenever a token is about to expire. You can have this logic run more frequently by reducing the token lifespan. In Okta Admin go to Security -> Authorization Servers -> (edit authorization server) -> Access Policies -> (edit access policy)

@jraadt's "silentLogin" method should work fine. If this method is run before the rest of the app loads, it will populate the token manager and then the other code will see that the user is authenticated. This could be done by having a loading/pre-authorization screen, by using the `config.isAuthenticated` method to call `silentLogin` the first time it is called, or by calling it in `config.onAuthRequired` (with fallback to redirect/popup).

Please let us know which method you find works best for your application.

**Comment by jraadt** [comment]
@aarongranick-okta Thanks for the reply. That makes sense and I think a combo of those function callbacks could help, but `getWithoutPrompt()` is not exposed in `OktaAuthService`. If that method was available then your solutions should work. Could that be added to `OktaAuthService` or is the a different way I can call `getWithoutPrompt()`?

**Comment by aarongranick-okta** [comment]
@jraadt Our other SDKs (React/Vue) expose the internal okta auth instance, but this appears to be a gap in our Angular SDK, since it is a private member. But there is no static state stored within the instance, you should be able to create another instance using the same configuration, and it will work fine.

```
import OktaAuth from '@okta/okta-auth-js'
let oktaAuth = new OktaAuth(/* same config you used to provide OKTA_CONFIG to angular service */)
```

We'll work on getting this gap filled in an upcoming release

**Comment by jraadt** [comment]
@aarongranick-okta Great! That would really help to expose the internal Okta auth instance. I look forward this. Thanks!

**Comment by swiftone** [comment]
Internal ref: OKTA-283293

**Comment by jraadt** [comment]
With the release of okta-angular 2.1.0 did you expose okta auth?

**Comment by swiftone** [comment]
@jraadt - looks like that PR fell through the cracks (https://github.com/okta/okta-oidc-js/pull/778 ).  I'll see if we're blocked on anything or if we can push that out.

**Comment by jraadt** [comment]
@swiftone - I really appreciate it. I'm really looking forward to it. Thanks!

**Comment by swiftone** [comment]
@jraadt - looks like it is blocked as we pull in typescript definitions, so we can't release it immediately.  Typescript is actively being worked on, so it shouldn't be much longer.  Sorry for the delays!

**Comment by jraadt** [comment]
I appreciate the quick response and looking into it. I look forward to it.

**Comment by maneeshsahu** [comment]
Hi @swiftone , Do we have an ETA for the internal auth js instance access? The PR doesnt seem to be merged as yet https://github.com/okta/okta-oidc-js/pull/778

**Comment by swiftone** [comment]
@maneeshsahu - Hmm, now that the TS support has been released there should be no blockers,  I'll check with the team.

**Comment by jraadt** [comment]
@swiftone - That would be incredible to get this released!

**Comment by jraadt** [comment]
@swiftone - It looks like 3.0 is released with this feature now. I can't wait to start using it. When will 3.0 be available on NPM?

**Comment by aarongranick-okta** [comment]
@maneeshsahu @jraadt Until the new version of the library is published on NPM, as a workaround does it work to do `(authService as any)._oktaAuth` ?

**Comment by jraadt** [comment]
I'm pulling directly from Github for now to get 3.0. How long will it be until it's available on NPM?

**Comment by shuowu** [comment]
@jraadt This `okta-angular` v3.0 is still waiting on changes from `okta-auth-js`, we are actively working on it now, but may still need several weeks to get the new major version of `okta-angular` released on npm.

**Comment by jraadt** [comment]
I appreciate your hard work on these libraries. I saw there was a 2.2.1 release and I just wanted to check in and see if there's a status update for when 3.0 will be available. Thanks!

**Comment by shuowu** [comment]
@jraadt Thanks for waiting on it! 

Some updates here:
* changes for `okta-auth-js` (v4.1) are mostly ready, we are still working on some testing/samples update work to make sure it's stable.
* after the release of `okta-auth-js@4.1`, we will integrate `okta-angular` with the new version of `okta-auth-js` and release it. Here is the PR to track the progress: https://github.com/okta/okta-angular/pull/5

FYI, `okta-angular` has been moved out of this monorepo, the new repo address is: https://github.com/okta/okta-angular

**Comment by jraadt** [comment]
@shuowu Thank you so much for the update! I really appreciate the communication you all have with the community. It helps greatly.

There looks to be a lot of good stuff in `okta-auth-js` 4.1 so I'm excited for that. I noticed the new `okta-angular` repo and was confused at first, but that makes sense now so thanks for clearing that up as well.

I look forward to the (hopefully) soon release of okta-angular 3.0.

**Comment by jraadt** [comment]
With the new okta-angular 3.0, okta-auth-js is exposed now and working properly. This issue can probably be closed.

**Comment by swiftone** [comment]
Closing out this issue as resolved, but touching on a few points that were raised in it's long and twisty history for anyone that finds this issue and is looking for resolution:

- the `okta-angular` repo has moved out of this collection and to a standalone repo here: https://github.com/okta/okta-angular
- the AuthJS (`okta-auth-js`) is the OktaAuthService as of version 3.x ( https://github.com/okta/okta-angular/releases/tag/okta-angular-3.0.0 )
- anyone interested in unusual auto renewal options with Angular might consider Okta's One Time Refresh Tokens now usable with SPAs - https://developer.okta.com/docs/guides/sign-into-spa/angular/before-you-begin/#refresh-tokens-and-spas
