### ISSUE TITLE
Can Security return a Fragment?

### ISSUE THREAD

**Issue by mathieux51** [okta/okta-oidc-js#246]
## Expected Behavior

Security returns a Fragment. 

## Actual Behavior

[This component](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/Security.js#L36) returns a `div` and threre is no easy way to style it.  

Can I create a PR to replace this `div` by a `Fragment`? 

It would solve a CSS bug in the project I'm working on.

**Comment by robertjd** [comment]
Hi @mathieux51 , thanks for the question.  I agree, I don't think it's necessary to wrap this in a div.  However I would consider it a breaking change if we took it out, since others may be somehow depending on that div in a CSS selector.  For now (until we release another major version) we could add a class name, e.g. `security-wrapper` to this div, so that it's easier to select?

**Comment by mathieux51** [comment]
@robertjd, Thanks for your response. Adding a className would do the trick. Do you want me do it?

**Comment by robertjd** [comment]
Thanks for the offer! This is a quick one so I just put up a PR, you can follow there as we take this through our release process.

**Comment by kylecesmat** [comment]
@robertjd @jmelberg-okta - I just hit this too, a fragment or returning `this.props.children` directly I feel would be a better solution, given I was not expecting this extraneous div to be added by the security provider.

Anyway, looking forward to this fix to land in the meantime, when are you anticipating this being released?

**Comment by robertjd** [comment]
Thanks @kylecesmat for the input!  We're working on a few other issues in react this week, so expect a release soon.  I've created a milestone for 2.0 of the react library, where I've created #280 to track the need to change this to a fragment.
