### ISSUE TITLE
OKTA-angular no way to detect invalid session, oktaAuth itself declared private in the library

### ISSUE THREAD

**Issue by SushanRajShakya** [okta/okta-oidc-js#370]
## I'm submitting this issue for the package(s):

- [x] okta-angular

## I'm submitting a:

- [x] Feature request

## Current behavior
There is not way to access the session variables in okta-angular, due to which even though i have signed out from the okta itself using its logout button, okta-angular's isAuthenticated( ) gives me true on response as the access token has not expired 

## Expected behavior
I need to be able to access the session variable in okta auth to validate the session so that i can ask the users to re-login or properly authenticate the session before doing anything

## Extra information about the use case/user story you are trying to implement
We have implemented SSO in our application along with a few other applications. Signing out from my application using DELETE sessions/me logs me out from my application and OKTA itself too but if i sign out of OKTA then my applications isAuthenticated( ) returns true i.e. Access token is still valid and there is no way for us to access the session validity

## Environment

- Package Version: 1.0.7
- Browser: Chrome
- OS: Ubuntu 18 LTS
- Node version (`node -v`): 8.14.0
- Other: Angular 5

**Comment by hongbinc** [comment]
Any update on this?

**Comment by swiftone** [comment]
Hi! Thanks for your question.  

The situation as described is actually Working As Intended - creating a session gives the app a signed token that is valid for the duration without requiring a round-trip to the server anytime you need to validate it.  As a side-effect, this means that the app won't know if the token has been revoked without an explicit check.

Tokens have a limited life-span, and are periodically refreshed ( and that refresh will fail if user explicitly logged out) so for most customers this is a feature and not a bug.  (Indeed, without this feature the moment you validate that a token is valid, you no longer know if it's NOW invalid, so every single decision that requires the user be authenticated would involve another round-trip to the server).  

If you have a need to explicitly validate that the still-alive token has not been revoked since the time it was received/last-refreshed we have APIs to do that.   Is that a need you have?
