### ISSUE TITLE
SecureRoute for '/' path has to be exact

### ISSUE THREAD

**Issue by dallashuggins** [okta/okta-oidc-js#437]
## I'm submitting this issue for the package(s): 
okta-react

## I'm submitting a:
Bug report

## Current behavior
When I do not specify `exact` in the `SecureRoute` for `Home`, the app never loads. When I go to load localhost:8080, the browser hangs with the spinning wheel. 

When I use the following code to add the routes, the page loads the Okta sign-on widget as it should. However, when I take out `exact`, the page stops loading. I get no errors in the console or anything, except for a `Throttling navigation to prevent the browser from hanging` warning. 
```
<SecureRoute exact path='/' component={Home}/>
<SecureRoute path='/sandbox' component={Sandbox} />
```

## Expected behavior

My `Home` component checks the authentication and redirects the user to login if not valid. The `Home` component's function is only to check auth and to house the navigation bar; below is all that is being returned from the component.
```
      <React.Fragment>
        <Navigation />
        <div className={css.container}>
          { this.props.children }
        </div>
      </React.Fragment>
```
Ideally the `Home` component is rendered each time a page loads so that the auth is checked and nav is rendered, along with the component content for the specific route. 

## Minimal reproduction of the problem with instructions
Remove `exact` from the `SecureRoute` with `path='/'`.

## Extra information about the use case/user story you are trying to implement
What I want to happen is for the routes to all be nested within the `Home` component, so that for every page the auth is checked and the navigation is rendered along with the content specific to that page. When I removed `exact`, this behavior worked temporarily, where the navigation displayed, auth was checked, and the specific component's content was rendered. However, after a little bit it stopped working and started just hanging there and will only render if I add `exact` to the `Home` component. 

I am new to using Okta and `okta-oidc-js` packages, so I can change this from "Bug Report" if it's just a matter of doing it a different way. Any help would be greatly appreciated!

## Environment

- Package Version: `^1.2.0`
- Browser: Chrome
- OS: macOS High Sierra
- Node version (`node -v`): `v10.15.3`

**Comment by swiftone** [comment]
Hi, thanks for the feedback!

I don't think this is a bug - React-Router uses `exact` to prevent (or the absence to allow) matching of partial routes.  Without `exact` every route will match `/`.   That said I can always be wrong about react-router or misunderstanding your situation.

I think you can achieve what you are looking for by not-exactly-nesting your routes.  Does the answer here cover your situation well? https://stackoverflow.com/questions/41474134/nested-routes-with-react-router-v4

**Comment by kraudensky** [comment]
I am also experiencing this issue. I'm wrapping my entire react app with an Okta login and I have a `<SecureRoute path='/' component={Home} />` component, then within the `<Home/>` component I've defined nested routes used to access the rest of the app. Without specifying the home route as `exact`, my app hangs while it calls my custom `onAuthRequired` method in an infinite loop (specifically because that method calls `history.push('/login')`), never rendering my actual login page. If I specify the SecureRoute's path as `exact` it works fine, but then I cannot render my nested route components at all.

This is the full code snippet that causes the app the hang:
```
function customAuthHandler({history}) {
    history.push('/login');
}

class Authenticator extends React.Component {
    render() {
        return (
            <Router>
                <Security
                    issuer={config.issuer}
                    client_id={config.client_id}
                    redirect_uri={config.redirect_uri}
                    onAuthRequired={customAuthHandler}>
                    <SecureRoute
                        path="/"
                        component={Home}/>
                    <Route
                        path="/implicit/callback"
                        exact
                        component={ImplicitCallback}/>
                    <Route
                        path="/login"
                        exact
                        render={() => (
                            <LoginScreen baseUrl={config.baseUrl} />
                        )}/>
                </Security>
            </Router>
        );
    }
}
```

I am currently working around this issue by not overriding the `<Security/>` component's `onAuthRequired` prop and just using the default Okta login screen. This then allows me to keep my secure route's path as `exact={false}`, successfully sign in, and still use the nested routes defined in my `<Home/>` component without any problems.

Since this is possible to implement using the default login page, it should be supported using the Okta Signin Widget or a completely custom login screen as well. Definitely seems like a bug.

**Comment by swiftone** [comment]
@kraudensky - Thanks for the feedback.  Unforunately, I think you're running afoul of the concept of routes in general (when combined with security requirements)

If you're saying that "/" (non-exact) is secured, then you are saying all routes should be secured (which causes your problem)  I think you need to have your Home component itself NOT be secured, and specify which of the nested routes DO need to be secured.

**Comment by kraudensky** [comment]
@swiftone I understand what you are saying, but the fact that the path is "/" in this case is only because I want my entire app to be secure. My secure route could instead have it's path set as "/topics" and I may want to be able to nest paths "/topics/topic1" and "/topics/topic2" inside "/topics" and define those routes inside a `<Topics/>` component. I would still run into the same issue.
Again, this is possible using the default login screen, so the fact that it isn't an option outside of that use case seems odd.

**Comment by swiftone** [comment]
> this is possible using the default login screen, so the fact that it isn't an option outside of that use case seems odd.

If I'm following your meaning, the "default login screen" is actually a redirect to an okta.com domain, which then sends you back - you never fully render a route on your local app without being authenticated, so this doesn't actually contradict the problem, it sidesteps it by being on a different domain.

This question (essentially: "How do I have '/login' as an exception to a non-exact '/' routing") is more of a routing question than an Okta SecureRoute question.  You might look into having an outer container that manages /login and passes everything else to SecureRoute, or there might be a few other ways of managing the priority or route decision-making, but those are outside of the scope of SecureRoute itself.   (Which doesn't mean we aren't interested in hearing and sharing any resolution you come up with - Have you asked on our forums?  https://devforum.okta.com/ )

I'm closing the issue as we don't have specific work to do on it, but feel free to comment on it with any workaround/solution you wish to share, or to reopen it/create a new issue if have a feature/bug related to this we could work on.

**Comment by chinanderm** [comment]
This one drove me nuts for a while as well, but all you need to do is utilize `react-router-dom`'s `Switch` wrapper component. It instructs the router to stop looking for additional path matches after the first matching route found. So, here is my solution:

```
<Router>
   <Security issuer={__oktaConfig.issuer}
      client_id={__oktaConfig.client_id}
      redirect_uri={__oktaConfig.redirect_uri}
      onAuthRequired={onAuthRequired}
   >
      <Switch>
         <Route path='/login' render={() => <Login baseUrl={__oktaConfig.base_url} />} />
         <Route path={__oktaConfig.callback_route} component={ImplicitCallback} />
         <SecureRoute path='/' component={MyWholeApplicationThatShouldBeSecured} />
      </Switch>
   </Security>
</Router>
```

I had the `Switch` in there but kept getting the redirect loop like you were, until I realized that I needed to move `Switch` _inside_ `Security`, then BAM -- it worked.

**Comment by kraudensky** [comment]
Wow, thank you @chinanderm! This works perfectly and is exactly what I was looking for. I believe at one point I also had a `Switch` outside of the `Security` component and just took it out when it didn't work.
Okta might consider mentioning this in the implementation docs since it's not at all clear that the `Switch` is necessary in order to get this use case to work properly.
