### ISSUE TITLE
TokenManager with custom storage using async getItem

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-oidc-js#640]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Right now we can't keep connected after reopening the app because the tokenManager is not calling the **setItem** when the user is authenticated, also we need to use `AsyncStorage` of `ReactNative` instead of `localStorage`, because object browsers are not supported in this platform, and the **getItem** method is asynchronous, how can we support this?

## Expected behavior
Be able to set and get the token, idtoken and refresh token with `AsyncStorage` of React Native, also to be able to use refresh token after reopening the app.

## Minimal reproduction of the problem with instructions
You can use this repo https://github.com/okta/samples-js-react-native/tree/master/custom-sign-in

## Environment

- Package Version: "@okta/okta-auth-js": "^2.11.0",
- Browser: N/A
- OS: iOS
- Other: "@okta/okta-react-native": "^1.3.0",

**Comment by IldarAbdullin-okta** [comment]
Hi @jdnichollsc ,

In order to restore access, id and refresh tokens you have to use `okta-react-native` SDK and its API. Auth JS SDK can't be used for the token management in that case
So, the idea is following:
- You use `okta-auth-js` for implementing your custom RN UI and getting session token
- You use `okta-react-native` for exchanging session token to access token. SDK saves tokens in secure storage and provides other token management capabilities

Hope this helps

**Comment by jdnichollsc** [comment]
Ohh excellent, I'm glad to hear that, thanks and have a happy new year!
