### ISSUE TITLE
Block third party cookies prevents full logout 

### ISSUE THREAD

**Issue by jeffsenn** [okta/okta-oidc-js#642]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ x ] Bug report  
- [ x ] Feature request
- [ ] Other (Describe below)

## Current behavior
If Block 3rd party cookies is enabled in a browser, there is no way to clear the MYDOMAIN.okta.com cookies (the call to /api/v1/session/me fails on a 401 during auth.logout() )
So a subsequent auth.login() will just re-submit those cookies and log the user in again (even if all local app state is cleared).
This is obviously a security concern as the user is unable to clear these cookies except by brute force thru the browser.

## Expected behavior

Suggest there there should be some way to clear these cookies.  For example a page hosted on MYDOMAIN.okta.com/logout that could be hit to clear the cookies.

## Minimal reproduction of the problem with instructions
From React sample app, do a login (with Block 3rd party cookies enabled) and then logout and see that cookies are not cleared.

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by jeffsenn** [comment]
Could be related to #580

**Comment by jeffsenn** [comment]
After updating all my packages this seems to work now - not sure what changed (maybe something was stuck at an old version).  Closing.

**Comment by garrettmac** [comment]
This is not resolving it for me. Anywhere I look the issue seems to be unaddressed (like on oktas developer forum https://devforum.okta.com/t/logout-third-party-cookies/4209/7). Is this just an api architectural gap? Were they didnt think of browsers and it's limitations? Doesn't seem framework or version specific.

**Comment by swiftone** [comment]
@garrettmac - What version of okta-auth-js and okta-react are you using?

Recent versions of okta-auth-js support a logout method that calls an API that shouldn't rely on cookies.  (i.e. doesn't use the `/sessions/me` API mentioned above)

In recent versions of okta-react you would call this using `authService.logout()` (See https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#show-login-and-logout-buttons-function-based )

Note that if you want to return the user to your app after logout instead of the okta site you will need to have a "post logout redirect uri" configured in the okta admin dashboard (this is an OIDC standard requirement)

Hope that helps, if it doesn't please open a new github issue describing your problem, as this issue is closed and further comments on it may not be noticed.  (Feel free to reference this issue in any new issue you open though)
