### ISSUE TITLE
SecureRoute exact=true

### ISSUE THREAD

**Issue by rogeralsing** [okta/okta-oidc-js#70]
In SecureRoute.js https://github.com/okta/okta-oidc-js/blob/8dfb16d3047b0a89a5c90a134285c8ab08de0020/packages/okta-react/src/SecureRoute.js#L57

There is no way to specify additional route props, e.g. `exact`

**Comment by mschaeffner** [comment]
I'd suggest that all props are passed down to `Route`, because `SecureRoute` should just act like a proxy to ensure authentication. I could create a pull request for this. But first, I'd like to see my PR_139 (https://github.com/okta/okta-oidc-js/pull/139) merge into master, as this also deals with `SecureRoute`, and I try to avoid merge conflicts later on.

**Comment by jmelberg-okta** [comment]
Thanks for the input all!

This issue is now resolved with #279 and released under `@okta/okta-react@1.1.0`.
