### ISSUE TITLE
AuthSdkError: Unable to retrieve OAuth redirect params cookie

### ISSUE THREAD

**Issue by krabouilleur** [okta/okta-oidc-js#714]
![BUG-OKTA](https://user-images.githubusercontent.com/53522372/77075732-16e07680-69f3-11ea-94ee-e423775fc544.PNG)
 

## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Keep getting ERROR Error: Uncaught (in promise): AuthSdkError: Unable to retrieve OAuth redirect params cookie when redirect from okta login

## Expected behavior
Login without error

## Minimal reproduction of the problem with instructions
login() -> redirect to login form (tonent) -> redirect to implicit/callback -> error (sometimes, not everytimes)

## Extra information about the use case/user story you are trying to implement

1.  want to be authenticated
2. I go to my website
3. I'm redirect to login form (not in my website but to the tonent login form) because the OktaAuthGuard redirect me to here
4. Then login form redirect me to the website : the implici/callback where there is a code
5. I've the bug message

![BUG-OKTA](https://user-images.githubusercontent.com/53522372/77075732-16e07680-69f3-11ea-94ee-e423775fc544.PNG)

## Environment

- Browser: Firefox
- OS: Windows 10
- Node version (`node -v`): v10.15.3
- Other:
"@angular/common": "^8.0.0",
"@angular/core": "^8.1.2",
"@angular/router": "^8.0.0",
"@okta/okta-angular": "^2.0.0",
"@okta/okta-auth-js": "^3.0.0",

**Comment by nharrisanalyst** [comment]
It Seems that a majority of the issues are this error 

AuthSdkError: Unable to retrieve OAuth redirect params cookie

see https://github.com/okta/okta-oidc-js/issues/706

This is because
1. the docs are really lacking in explanation they are filled with recipes that IMO as a developer and looking at the questions do not work.
2. You should consider having a section on how to trouble shoot this error on every SPA and vanilla JavaScript page.
3. This error mainly comes from tools that are being used for the wrong reason and this is exasperated because the okta docs are not explicit enough on when to use what tool for when and how. 

I myself would've never have figured this error out with the updated readme for Okta react 2.0 
as you see this documentation is a lot more explicate on the specific tools in this toolbox.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/16217396/77116564-9ec38200-69ed-11ea-817e-e58c5ce73b69.png">

**Comment by krabouilleur** [comment]
i fix the problem like this (not beautifull but working)
0. I go to my path /myPageWithGuard
1. OktaAuthguard redirect to the login page okta
2. I write username + password then OK
3. Okta redirect to /implici/callback
4. there is the error
5. in my code I write : if there is okta error : this.router.navigate([ ' myPageWithGuard' ]);
6. Guard redirect me to implicit/callback again
7. no error, i'm redirected to myPageWithGuard


(not beautifull but works evenf if this not resolve the problem definitly)

**Comment by swiftone** [comment]
@krabouilleur - Thanks for the report.  The errors you describe sound like you are having a race condition between multiple reads of the short-term cookies we use before the redirect.  Can you offer some details about how you're calling the code?  Do you encounter this problem with simple example code from the README?

**Comment by swiftone** [comment]
Closing as stale - if this continues to be a problem feel free to reopen with details!
