### ISSUE TITLE
Revoke is not getting called correctly in authService.logout

### ISSUE THREAD

**Issue by luispeerez** [okta/okta-oidc-js#753]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

When using the `authService` `logout` method, the app doesn't revoke the access token for that session (it is still valid to make other requests). 

By checking the okta-auth-js implementation  https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/browser/browser.js#L274 I saw that some options need to be passed to the logout function of the auth service (which is a bridge between my application and `okta-auth-js` `signOut` function https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/AuthService.js#L219

The problem that I got is that actually passing some options (that are not detailed in the docs):
```
  const token = await authService.getAccessToken(); // I have confirmed that this is the correct access token

  authService.logout({
    revokeAccessToken: true,
    accessToken: { accessToken: token },
  });
```

 there is actually an API call to the revoke endpoint (https://developer.okta.com/docs/reference/api/oidc/#revoke). But it hangs because it requires the user to put some credentials, which shouldn't be the correct behaviour.

This is how the revoke API call is done:
METHOD: POST
`REQUEST URL` : https://mydomain/oauth2/default/v1/revoke
Authorization: Basic <client id in base 64> // As seen in the token.js code of `okta-auth-js` https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/token.js#L43

Form Data:
`token_type_hint` : `access_token`
`token`: `<my_access_token>`

And this is what the browser displays while the request is in pending state: 
![Screenshot from 2020-04-21 16-19-45](https://user-images.githubusercontent.com/3952671/79916127-cf804800-83ed-11ea-8733-7204557a548b.png)

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by luispeerez** [comment]
Using okta-react 3.0.1 version

**Comment by swiftone** [comment]
@luispeerez - At this time the okta-react (as well as our other front-end SDKs)  are not intended to revoke tokens at  logout, but I've push your request up as a feature request.

Internal ref: OKTA-295188

**Comment by ch-tactica** [comment]
Huh? If it's not expected to revoke tokens at logout.... why in the world is it calling the revoke endpoint automatically when you call authService.logout?????

**Comment by swiftone** [comment]
@ch-tactica @luispeerez - I sit corrected, logout() calls the okta-auth-js signOut() and that was changed to include revokeToken() in okta-auth-js 3.0 (https://github.com/okta/okta-auth-js/releases/tag/%40okta%2Fokta-auth-js%403.0.0) - I forgot that change.

This issue seems identical to https://github.com/okta/okta-auth-js/issues/439, and as you can see from the comments there I've been unable to reproduce the symptoms.  I'll continue to dig, but if anyone can reach out to our support team at developers@okta.com and share details of your setup we will see if we can get everything working (and hopefully discover the cause for other impacted developers).

**Comment by ch-tactica** [comment]
@swiftone Thanks for the context, if I have time later I'll see if I can send you those details. I will try rolling back to an older release for now to see if that works.

**Comment by Derifgyn** [comment]
@swiftone Reviving this because I may have some help here.

I emailed developers@okta.com but I think I've figured out what may be happening.

If the project authentication method is set to "client_secret_basic" the revoke endpoint requires a base64 encoded clientId:clientSecret authorization header, otherwise it just requires a base64 clientId authorization header.

I'd imagine, like mine, people who are seeing this issue are seeing it because they have (incorrectly?) set their Okta Project to use "client_secret_basic" instead of "none". 

This issue was likely not bubbling up before because prior to the usage of the /revoke endpoint none of the method calls made such a requirement re: needing the client secret in an auth header.

<img width="849" alt="Screen Shot 2020-08-12 at 9 54 41 PM" src="https://user-images.githubusercontent.com/57924832/90086168-c6dab700-dce7-11ea-87a8-a3ed70e519af.png">
<img width="820" alt="Screen Shot 2020-08-12 at 9 55 42 PM" src="https://user-images.githubusercontent.com/57924832/90086171-cb06d480-dce7-11ea-8b65-531f6aa64acb.png">

I'm not sure the proper solution other than either one of the following: 
- switching okta-auth-js to use /logout instead of /revoke (why the change, and what's the actual difference?)
- changing the project to "none", but our problem with that is we use the same project in non-client facing scenarios as well, IE in a middleware service that calls introspect with the secret to check the call is from an authorized source - is this stil lan incorrect use case?

**Comment by hicaro** [comment]
@Derifgyn who did you update it to `none`? I tried using the [Update Application](https://developer.okta.com/docs/reference/api/apps/#update-application) endpoint and I got this error:

```json
{
    "errorCode": "E0000001",
    "errorSummary": "Api validation failed: token_endpoint_auth_method",
    "errorLink": "E0000001",
    "errorId": "oaeDWcq_xS-RE6fDhEJqVRdEw",
    "errorCauses": [
        {
            "errorSummary": "token_endpoint_auth_method: 'token_endpoint_auth_method' is invalid. Valid values: [client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt]."
        }
    ]
}
```

@swiftone is there a way to update this on the Admin console?

**Comment by swiftone** [comment]
@hicaro - as an Okta user, this is decided when you initially pick the "type" of the application (Web/SPA/Native/etc).  I'm not aware of any way to change that choice on the console, only to create a new application, but you can contact our support team at developers@okta.com to see if they some options that aren't publicly available.

**Comment by hicaro** [comment]
@swiftone thank you! I believe that the set of apps I have were all created as Web instead of SPA. That explains why I cannot set it to `none`.

**Comment by aarongranick-okta** [comment]
The current version of `okta-auth-js` supports both SPA and web applications. The `signOut` method will revoke tokens and send the correct headers for "client basic secret", if enabled: https://github.com/okta/okta-auth-js/blob/master/lib/oidc/revokeToken.ts#L54
