### ISSUE TITLE
After Login unable to redirected to dashboard after implicit/callback 

### ISSUE THREAD

**Issue by Narendrakumar-Vanamala** [okta/okta-oidc-js#783]
Am using okta-angular SDK to implement okta login.

Localhost everything works fine - Login/Logout & redirection flow.
But when am moved to production - After login redirection not happening after implict/callback trigger.

https://localhost:4200/implicit/callback - works fine no more issues.
https://{Production Port number}:/implicit/callback - redirection not happening getting 404 error.

Please help me on this to resolve this one.

## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular - Am using this one to implement okta login.
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
After login - redirected to implicit/callback URL - After this am getting 404 error.

## Expected behavior
After login - redirected to implicit/callback URL - After this redirected to landing page(dashboard/home) page what ever we defined in the app routing module based on the path.

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by mraible** [comment]
You have to setup your web server so it's SPA-aware. That is, all 404s should redirect to index.html.

**Comment by Narendrakumar-Vanamala** [comment]
Thanks for the update @mraible 

Please let me know what are the configurations required in Tomcat.

**Comment by Narendrakumar-Vanamala** [comment]
I have configured Tomcat SPA aware by using the below configuration in Tomcat 9.0 server

1. created new file called rewrite.config file in WEB-INF folder and  added the below configuration in the file
                
                RewriteRule ^/implicit/callback(.*)$ /index.html [L]
                RewriteRule ^/dashboard(.*)$ /index.html [L]

2. created context.xml file in META-INF folder and added the below code

                <?xml version="1.0" encoding="UTF-8"?>
                <Context>  
                  <Valve className="org.apache.catalina.valves.rewrite.RewriteValve" />
                </Context>
                
Restarted the tomcat server and access the application by logging into OKTA console and getting the same error as below

HTTP Status 404 – Not Found
Type Status Report

Message /de-assessment-dev/implicit/callback

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.19

The url is "https://server hostname:port no/angular application name/implicit/callback?code=xxx&state=xxx"     

Please provide us the steps to resolve the issue.

**Comment by mraible** [comment]
@Narendrakumar-Vanamala This [Stack Overflow Q & A](https://stackoverflow.com/questions/28767585/tomcat-8-url-rewrite) has some solutions that should work.

**Comment by Narendrakumar-Vanamala** [comment]
@mraible  Thanks for your support. Let's apply the solution and get back to you.

**Comment by Narendrakumar-Vanamala** [comment]
@mraible  Please suggest on the below one.

Hi,

I have followed the steps in the link provided by you and I am still getting the same error.
Please find below the steps which i have done

Created the file rewrite.config inside WEB-INF folder and added the following code

RewriteCond %{REQUEST_URI} ^/(css|img|js|partials|rest|favicon).*$
RewriteRule ^.*$ - [L]

RewriteRule ^.*$ /index.html [L,QSA]

created another file context.xml under META-INF folder and added the below code

<?xml version="1.0" encoding="UTF-8"?>
<Context>  
  <Valve className="org.apache.catalina.valves.rewrite.RewriteValve" />
  
</Context>

Restarted the server after adding the above and getting the same error as i was getting before.
Please help us to resolve this issue.

**Comment by mraible** [comment]
I think you might have better luck posting your questions to Stack Overflow. I haven't worked with Tomcat in 5 years so I'd just be guessing.

**Comment by aarongranick-okta** [comment]
@Narendrakumar-Vanamala Our samples assume that you have path-based routing setup for your SPA application. As @mraible has pointed out, this does require some server-side configuration. This is the recommended mode. If possible, get the "wildcard handler" setup on your server so that paths such as `/implicit/callback` will serve the page with your SPA app.

However, if this is not possible you could avoid server setup by setting the "root path" of your application as the callback, ie `http://localhost:4200` (or whatever URL you are using in production).  

If you are handling the callback on the root, you should have some code at the very beginning which can detect if you are handling a callback (if using PKCE flow you can look for "code" as a query parameter in the URL). 

If your app is in "callback mode" it should immediately call handleAuthentication: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-angular#oktaauthhandleauthentication

When handling the callback this way it is important that your app NOT try to determine if the user is authenticated before handling the callback, or you may create a parallel/race condition.

**Comment by swiftone** [comment]
Closing this issue as stale - if this continues to be a problem please feel free to reopen with any additional details.
