### ISSUE TITLE
okta-vue - why is getAccessToken async?

### ISSUE THREAD

**Issue by gaastonsr** [okta/okta-oidc-js#96]
Is there a reason why `getAccessToken` is async? as far as I see there is nothing async going on in the function. Would you accept a PR?

https://github.com/okta/okta-oidc-js/blob/f6f66aa3dfde922b4af5d80df655f07f7d37e5b0/packages/okta-vue/src/Auth.js#L44

Thanks.

**Comment by lboyette-okta** [comment]
We ultimately want the flexibility to swap out the `tokenManager` from `okta-auth-js` with something that may not use synchronous storage. Currently, the `tokenManager` aggressively renews tokens when it notices they're going to expire, which enables synchronous retrieval. This has a few issues:

1) It's inefficient - it renews tokens you may never use. A token has a 5 min timeout, but a user could sit on the page for 20 min without doing anything
2) It causes race conditions - it's possible to synchronously get a token while the `tokenManager` is renewing it. You'd send this expired token to your resource server, when the user actually has a valid session.

If/when we replace the `tokenManager`, the reasoning will be more apparent.

**Comment by gaastonsr** [comment]
It makes sense. Thanks.

**Comment by jakehockey10** [comment]
@lboyette-okta , what is the expectation on replacing TokenManager?  My issue is that with the new version of the `okta-angular` library, I no longer can access the TokenManager.  I even tried to bring in the `okta-auth-js` library and create the object myself, but I want the instance that the `OktaAuthService` is using.  The reason I want access to the TokenManager is so that I can listen to the `refresh` event and go `getUser` again, avoiding the race condition you mention above.

**Comment by fantapop** [comment]
The generated api open api client from https://swagger.io/tools/swagger-codegen/ allows fetching the access token from a method before each api call.  Unfortunately they do not allow async calls there so I'm unable to use this functionality.  It would be nice to provide both sync and async versions of this call.
